version: '3.8'

services:
  artifacts-bot:
    build: .
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      # API_TOKEN should be provided via environment variable or .env file
      - API_TOKEN=${API_TOKEN}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s